apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"bitpin-app","namespace":"bitpin-task"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bitpin-app"}},"template":{"metadata":{"labels":{"app":"bitpin-app"}},"spec":{"containers":[{"env":[{"name":"DJANGO_SETTINGS_MODULE","value":"Exchange.settings"},{"name":"DATABASE_HOST","valueFrom":{"secretKeyRef":{"key":"host","name":"bitpin-cluster-app"}}},{"name":"DATABASE_PORT","valueFrom":{"secretKeyRef":{"key":"port","name":"bitpin-cluster-app"}}},{"name":"DATABASE_NAME","valueFrom":{"secretKeyRef":{"key":"dbname","name":"bitpin-cluster-app"}}},{"name":"DATABASE_USER","valueFrom":{"secretKeyRef":{"key":"user","name":"bitpin-cluster-app"}}},{"name":"DATABASE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"bitpin-cluster-app"}}}],"image":"yasaman664/bitpin-task:latest","livenessProbe":{"httpGet":{"path":"/healthz/","port":8000},"initialDelaySeconds":10,"periodSeconds":20},"name":"bitpin-app","ports":[{"containerPort":8000}],"readinessProbe":{"httpGet":{"path":"/healthz/","port":8000},"initialDelaySeconds":5,"periodSeconds":10},"volumeMounts":[{"mountPath":"/app/Exchange/static","name":"static-volume"},{"mountPath":"/app/Exchange/media","name":"media-volume"}]}],"volumes":[{"emptyDir":{},"name":"static-volume"},{"emptyDir":{},"name":"media-volume"}]}}}}
  creationTimestamp: "2025-11-07T11:59:54Z"
  generation: 18
  name: bitpin-app
  namespace: bitpin-task
  resourceVersion: "48068"
  uid: 0a4d233f-34d8-4e4e-8284-a2c4c405a740
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bitpin-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-07T18:36:32+03:30"
      creationTimestamp: null
      labels:
        app: bitpin-app
    spec:
      containers:
      - env:
        - name: DJANGO_SETTINGS_MODULE
          value: Exchange.settings
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: bitpin-cluster-app
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: bitpin-cluster-app
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: dbname
              name: bitpin-cluster-app
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: bitpin-cluster-app
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bitpin-cluster-app
        image: yasaman664/bitpin-task:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: bitpin-app
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/Exchange/static
          name: static-volume
        - mountPath: /app/Exchange/media
          name: media-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: static-volume
      - emptyDir: {}
        name: media-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-07T15:06:38Z"
    lastUpdateTime: "2025-11-07T15:06:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-07T13:04:49Z"
    lastUpdateTime: "2025-11-07T15:13:30Z"
    message: ReplicaSet "bitpin-app-b776cb8bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
