apiVersion: v2
name: bitpin-app
description: A Helm chart for Bitpin Task Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - bitpin
  - django
  - postgresql
maintainers:
  - name: Yasaman Gholamian
